[package]
name = "wavrw"
version = "0.1.0"
edition = "2021"
description = "WAV file metadata read/write utility"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.1.1", features = ["derive"] }
