[package]
name = "wavrw"
version = "0.1.0"
edition = "2021"
description = "WAV file metadata read/write utility"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.68"
binrw = "0.13.3"
clap = { version = "4.1.1", features = ["derive"] }
hex = "0.4.3"
hexdump = "0.1.1"
itertools = "0.12.0"
paste = "1.0.14"

[dev-dependencies]
criterion = { version = "0.4", features = ["html_reports"] }

[profile.release]
overflow-checks = true

[[bench]]
name = "my_benchmark"
harness = false
