[package]
name = "wavrw"
version = "0.1.0"
edition = "2021"
description = "WAV file metadata read/write utility"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.68"
clap = { version = "4.1.1", features = ["derive"] }
hex = "0.4.3"
nom = "7.1.2"
